title: The new born programmer
author: pro-panda
subtitle: The life of a new-born programmer

url: "https://nle1.github.io"

footer_only_homepage: true
footer_url: "https://github.com/pro-panda"
footer_text: "Theme by pro-panda"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
  style: compressed
  sass_dir: css

navbar:
  - name: "About"
    link: "about"
  - name: "Resume"
    absolute-link: "http://nle1.github.io/resume.pdf"

# Google services
google_analytics: UA-156047559-1
